name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - parameters-plain-test-file
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com

jobs:
  test-action: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vmware-labs/vmware-image-builder-action@showing-violations
        with:
          path: '/'
          config: '.vib'
          pipeline: 'vib-pipeline.json'
          runtime_parameters_file: ${{ needs.get-chart.outputs.chart }}/runtime-parameters.yaml
          retry-count: 5
          backoff-intervals: '[100, 500, 1000, 2000, 5000]'
